### ISSUE TITLE
Error In function 'memory_is_too_low'

### ISSUE THREAD

**Issue by yito24** [elastio/elastio-snap#116]
I can't install rpm built from the latest source code on RHEL6.x / CentOS 6.x / Oracle Linux6.x
It occur a lot of errors in make.log.

<pre>
[root@Cent69 ~]# rpm -Uvh ./dkms-elastio-snap-0.10.16-1.el6.noarch.rpm 
Preparing...                ########################################### [100%]
   1:dkms-elastio-snap      ########################################### [100%]
Loading new elastio-snap-0.10.16 DKMS files...
Building for 2.6.32-696.el6.x86_64
Building initial module for 2.6.32-696.el6.x86_64
Error! Bad return status for module build on kernel: 2.6.32-696.el6.x86_64 (x86_64)
Consult /var/lib/dkms/elastio-snap/0.10.16/build/make.log for more information.
warning: %post(dkms-elastio-snap-0.10.16-1.el6.noarch) scriptlet failed, exit status 10
</pre>

make.log
<pre>
DKMS make.log for elastio-snap-0.10.16 for kernel 2.6.32-696.el6.x86_64 (x86_64)
Wed Apr 27 10:31:43 JST 2022
make: Entering directory `/usr/src/kernels/2.6.32-696.el6.x86_64'
  CC [M]  /var/lib/dkms/elastio-snap/0.10.16/build/elastio-snap.o
/var/lib/dkms/elastio-snap/0.10.16/build/elastio-snap.c: In function 'memory_is_too_low':
/var/lib/dkms/elastio-snap/0.10.16/build/elastio-snap.c:3165: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'totalram'
/var/lib/dkms/elastio-snap/0.10.16/build/elastio-snap.c:3165: error: 'totalram' undeclared (first use in this function)
/var/lib/dkms/elastio-snap/0.10.16/build/elastio-snap.c:3165: error: (Each undeclared identifier is reported only once
/var/lib/dkms/elastio-snap/0.10.16/build/elastio-snap.c:3165: error: for each function it appears in.)
/var/lib/dkms/elastio-snap/0.10.16/build/elastio-snap.c:3171: error: implicit declaration of function 'si_mem_available'
/var/lib/dkms/elastio-snap/0.10.16/build/elastio-snap.c: In function 'elastio_snap_wait_for_release':
/var/lib/dkms/elastio-snap/0.10.16/build/elastio-snap.c:5522: warning: passing argument 2 of '__read_once_size' discards qualifiers from pointer target type
include/linux/compiler.h:173: note: expected 'void *' but argument is of type 'volatile long int *'
make[1]: *** [/var/lib/dkms/elastio-snap/0.10.16/build/elastio-snap.o] Error 1
make: *** [_module_/var/lib/dkms/elastio-snap/0.10.16/build] Error 2
make: Leaving directory `/usr/src/kernels/2.6.32-696.el6.x86_64'
</pre>

**Comment by e-kov** [comment]
@yito24 thanks for the bug report.
Unfortunately, we do not support this driver for CentOS 6 because CentOS 6 reached EOL a long time ago. The issue occurs in some other newer kernel versions, not just `2.6.32`, so it will be fixed soon.
